# -*- coding: utf-8 -*-

"""Installation script."""


#------------------------------------------------------------------------------
# Imports
#------------------------------------------------------------------------------

import os
import os.path as op
from textwrap import dedent
from setuptools import setup

from setuptools.command.develop import develop as _develop
from setuptools.command.install import install as _install


#------------------------------------------------------------------------------
# Setup
#------------------------------------------------------------------------------

def _create_loader_file():
    """Create a Python script that imports phycontrib in the
    plugins directory. This ensures that phycontrib's plugins are always
    loaded by phy."""
    # Make sure the plugins directory exists.
    plugins_dir = op.expanduser('~/.phy/plugins/')
    if not op.exists(plugins_dir):
        os.makedirs(plugins_dir)
    # Create the script if it doesn't already exist.
    path = plugins_dir + 'phycontrib_loader.py'
    if op.exists(path):
        return
    with open(path, 'w') as f:
        f.write(dedent("""
                # Automatically generated by phycontrib's installer.
                # This imports all of phycontrib's plugins when loading phy.
                import phycontrib
                """).lstrip())


class develop(_develop):
    def run(self):
        """Create the loader file once python setup.py develop succeeds."""
        _develop.run(self)
        _create_loader_file()


class install(_install):
    """Create the loader file once python setup.py install succeeds."""
    def run(self):
        _install.run(self)
        _create_loader_file()


setup(
    name='phycontrib',
    version='1.0',
    license='BSD',
    description='phycontrib',
    long_description='',
    author='Kwik Team',
    author_email='cyrille.rossant at gmail.com',
    url='https://phy.cortexlab.net',
    packages=['phycontrib'],
    classifiers=[
        'Development Status :: 4 - Beta',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: BSD License',
        'Natural Language :: English',
        "Programming Language :: Python :: 2",
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
    ],
    cmdclass={'develop': develop,
              'install': install},
)
